enableVersioning: true
handle: emergencyMessage
name: 'Emergency Message'
propagationMethod: all
siteSettings:
  34463b82-dd3f-441c-b9c6-59c351e847aa:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
