enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  34463b82-dd3f-441c-b9c6-59c351e847aa: # Craft
    enabledByDefault: true
    hasUrls: true
    template: _page
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 0f9bddc9-659f-4907-82a2-028748c7f504
type: structure
