contentColumnType: string(255)
fieldGroup: 1e0f22f0-2c77-45f2-a8dd-9405520e5ce0 # Emergency Message
handle: eMsg_linkUrl
instructions: ''
name: 'Link URL to "Learn More"'
searchable: false
settings:
  maxLength: '255'
  placeholder: null
  types:
    - url
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
