contentColumnType: text
fieldGroup: 7902e1c8-6594-4a40-8c22-e510c7a0b9e8 # Hero
handle: hero_introCopy
instructions: ''
name: 'Intro Copy'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: ''
  cleanupHtml: true
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Simple.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: ''
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
